### ISSUE TITLE
Cannot access protected property ProcessWire\Pageimage::$original

### ISSUE THREAD

**Issue by matjazpotocnik** [gebeer/FieldtypeImageReference#1]
Hi, thanks for the module. When I select an image from a predefined folder, after save, I get:

Cannot access protected property ProcessWire\Pageimage::$original in /wire/core/PageimageVariations.php:256

PHP Notice: Undefined property: ProcessWire\PageimageDebugInfo::$original in ...\wwwroot\wire\core\PageimageDebugInfo.php:71

It might be related to PHP 7.4 or might be something with my installation or other hooks. I can't provide more info right now but will dig into this later. 

edit: it's better if I set 'allowSelf' => false in populateImages(), but after every page refresh, new variations are created...strange

**Comment by gebeer** [comment]
Thank you for reporting. Never had this occur in my tests. Haven't tested on PHP 7.4 yet.
The 'allowSelf' => true is necessary so that PW can identify if the file is a variation or not. When set to false, the test fails and the new creations are created.
I am about to change the logic for Pageimages from folder and will update the repo soon. Please follow and use the updated version, once available.

**Comment by gebeer** [comment]
I released a new version with amended logic for pagimage creation. Please try https://github.com/gebeer/FieldtypeImagePicker/tree/v1.1.1

**Comment by matjazpotocnik** [comment]
The new version is working ok, no more errors, no more duplicating images.

After update and modules refresh, I get this error:

> ProcessModule: Failed module dependency: FieldtypeImagePicker requires MySQL

I'm running MySQL 5.7.9 (I think so). I'm not sure PW has support for detecting MySQL version?

I think it would be good to add a trailing slash to folderpath if the user forgets. Or just mention it in notes. How about allowing the folder to be in /site/assets instead of (or in addition to) /site/templates?

**Comment by gebeer** [comment]
> 

    ProcessModule: Failed module dependency: FieldtypeImagePicker requires MySQL

> I'm running MySQL 5.7.9 (I think so). I'm not sure PW has support for detecting MySQL version?

I just removed the MySQL requirement from the module. Seems like PW can only handle PHP requirement. So the error should be gone.
> I think it would be good to add a trailing slash to folderpath if the user forgets. Or just mention it in notes.

The trailing slash is already being added programmaticly. Or did you experience a problem when not adding it?
> How about allowing the folder to be in /site/assets instead of (or in addition to) /site/templates?

I'll maybe add this as a feature in a future version.

I'm closing this issue. Please open separate issues for further problems or other feature requests. Thank you.
