### ISSUE TITLE
Missing responsive image thumbnail preview

### ISSUE THREAD

**Issue by Ragnarokkr** [gebeer/FieldtypeImageReference#2]
The preview image is set by default to 200px or 100px but isn't responsive. When it falls on template's fields layout where container is pretty narrow (20/30%) the image doesn't fit the space by resizeing itself but goes outside the boundaries.
 
![imageexternalreference](https://user-images.githubusercontent.com/893472/73124490-51520800-3f9c-11ea-975b-04d7559b7a85.png)

It would be great if it could responsively adapt to its container.

BTW, great work. Can't wait its supporting for multiple images. Now I'm using repeaters for galleries but with that change will be a charm to build image galleries.

**Comment by gebeer** [comment]
Thanks for reporting. Just pushed a fix for this. Use latest master. There still is a min-width of 100px for the image containers, though. Otherwise the image description text would become unreadable. 
Please let me know if it works now and I can close this issue.

**Comment by Ragnarokkr** [comment]
Sorry for late reply. It seems the issue still remains. I tried to change the template layout but the image still get clipped out when container is not large enough. In screenshot the image field is sized at 20% and gallery is the remaining 80%.

What I did see also is that by referencing from system folder there's no way to define a description as is possibile to do in default `InputImage` field. I saw this because I'm trying to implement *featured* and *gallery* fields for a generic post keeping a common default path for the images (which would change if referencing the images from another page, in case this last one would change in future for some reason).

Also I noticed that images from selector don't activate the scrolling, making the selection a bit hard especially on desktop forcing to scroll a lot. :disappointed: 

![screenshot-api mediagold local-2020 02 02-18_06_34](https://user-images.githubusercontent.com/893472/73611879-ebdac880-45e6-11ea-99a1-c3d286666879.png)

**Comment by gebeer** [comment]
I pushed a patch. Now also the preview image should be responsive, even when inside a very tight container like in your situation.
I am not planning on implementing descriptions for folder images atm, sorry. You'd need an extra field for that.
The missing scroll that you describe would only be necessary in edge cases like yours where there is no horizontal space and all the thumbs line up vertically. I will also not implement this atm. You might want to think over the arrangement of your gallery repeater on the page edit screen.

Please report if the responsive issue for the preview image is now resolved. Thank you.
